export interface ChatMessage {
  id: string;
  sender: string;
  message: string;
  timestamp: string;
  type: 'player' | 'ai' | 'table' | 'system';
  action?: string;  // Optional action text (e.g., "raised to $50") for AI messages
}

/**
 * Backend message format (before transformation to ChatMessage).
 * Uses the same message_type values as ChatMessage.type.
 */
export interface BackendChatMessage {
  id?: string;
  sender: string;
  content: string;
  timestamp: string;
  message_type: ChatMessage['type'];
  action?: string;  // Optional action text for AI messages
}

/**
 * Tone options for targeted chat suggestions.
 */
export type ChatTone = 'encourage' | 'antagonize' | 'confuse' | 'flatter' | 'challenge';

/**
 * A targeted chat suggestion generated by the AI.
 */
export interface TargetedSuggestion {
  text: string;
  tone: ChatTone;
}

/**
 * Response from the targeted-chat-suggestions endpoint.
 */
export interface TargetedSuggestionsResponse {
  suggestions: TargetedSuggestion[];
  targetPlayer: string | null;
}