export interface ChatMessage {
  id: string;
  sender: string;
  message: string;
  timestamp: string;
  type: 'player' | 'ai' | 'table' | 'system';
  action?: string;  // Optional action text (e.g., "raised to $50") for AI messages
  phase?: string;   // Optional game phase for card-deal messages (e.g., "flop")
  cards?: string[]; // Optional card strings for card-deal messages (e.g., ["A♠", "K♦"])
  win_result?: WinResult; // Optional structured winning hand data
}

/** Structured data for winning hand display in chat */
export interface WinResult {
  winners: string;
  pot: number;
  is_showdown: boolean;
  hand_name?: string;          // Only for showdown
  winner_cards?: string[];     // Hole cards, e.g. ["A♠", "K♠"]
  community_cards?: string[];  // Board, e.g. ["Q♠", "J♠", "10♠", "5♥", "2♦"]
  winning_combo?: string[];    // Best 5-card combo rank names, e.g. ["A", "K", "Q", "J", "10"]
}

/**
 * Backend message format (before transformation to ChatMessage).
 * Uses the same message_type values as ChatMessage.type.
 */
export interface BackendChatMessage {
  id?: string;
  sender: string;
  content: string;
  timestamp: string;
  message_type: ChatMessage['type'];
  action?: string;  // Optional action text for AI messages
  phase?: string;   // Optional game phase for card-deal messages
  cards?: string[]; // Optional card strings for card-deal messages
  win_result?: WinResult; // Optional structured winning hand data
}

/**
 * Psychological manipulation goals for targeted chat suggestions.
 */
export type ChatTone = 'tilt' | 'bait' | 'needle' | 'goad' | 'bluff' | 'befriend';

/**
 * Length modifier for chat suggestions.
 */
export type ChatLength = 'short' | 'long';

/**
 * Intensity modifier for chat suggestions.
 */
export type ChatIntensity = 'chill' | 'spicy';

/**
 * A targeted chat suggestion generated by the AI.
 */
export interface TargetedSuggestion {
  text: string;
  tone: ChatTone;
}

/**
 * Response from the targeted-chat-suggestions endpoint.
 */
export interface TargetedSuggestionsResponse {
  suggestions: TargetedSuggestion[];
  targetPlayer: string | null;
  fallback?: boolean;
  error?: string;
}

/**
 * Post-round chat tones based on win/loss outcome.
 * Winners: gloat, humble
 * Losers: salty, gracious
 */
export type PostRoundTone = 'gloat' | 'humble' | 'salty' | 'gracious';

/**
 * A post-round chat suggestion.
 */
export interface PostRoundSuggestion {
  text: string;
  tone: PostRoundTone;
}

/**
 * Response from the post-round-chat-suggestions endpoint.
 */
export interface PostRoundSuggestionsResponse {
  suggestions: PostRoundSuggestion[];
  fallback?: boolean;
  error?: string;
}