export interface ChatMessage {
  id: string;
  sender: string;
  message: string;
  timestamp: string;
  type: 'player' | 'ai' | 'table' | 'system';
  action?: string;  // Optional action text (e.g., "raised to $50") for AI messages
  phase?: string;   // Optional game phase for card-deal messages (e.g., "flop")
  cards?: string[]; // Optional card strings for card-deal messages (e.g., ["A♠", "K♦"])
}

/**
 * Backend message format (before transformation to ChatMessage).
 * Uses the same message_type values as ChatMessage.type.
 */
export interface BackendChatMessage {
  id?: string;
  sender: string;
  content: string;
  timestamp: string;
  message_type: ChatMessage['type'];
  action?: string;  // Optional action text for AI messages
  phase?: string;   // Optional game phase for card-deal messages
  cards?: string[]; // Optional card strings for card-deal messages
}

/**
 * Psychological manipulation goals for targeted chat suggestions.
 */
export type ChatTone = 'tilt' | 'false_confidence' | 'doubt' | 'goad' | 'mislead' | 'befriend';

/**
 * Length modifier for chat suggestions.
 */
export type ChatLength = 'short' | 'long';

/**
 * Intensity modifier for chat suggestions.
 */
export type ChatIntensity = 'chill' | 'spicy';

/**
 * A targeted chat suggestion generated by the AI.
 */
export interface TargetedSuggestion {
  text: string;
  tone: ChatTone;
}

/**
 * Response from the targeted-chat-suggestions endpoint.
 */
export interface TargetedSuggestionsResponse {
  suggestions: TargetedSuggestion[];
  targetPlayer: string | null;
  fallback?: boolean;
  error?: string;
}

/**
 * Post-round chat tones based on win/loss outcome.
 * Winners: gloat, humble
 * Losers: salty, gracious
 */
export type PostRoundTone = 'gloat' | 'humble' | 'salty' | 'gracious';

/**
 * A post-round chat suggestion.
 */
export interface PostRoundSuggestion {
  text: string;
  tone: PostRoundTone;
}

/**
 * Response from the post-round-chat-suggestions endpoint.
 */
export interface PostRoundSuggestionsResponse {
  suggestions: PostRoundSuggestion[];
  fallback?: boolean;
  error?: string;
}