services:
  # Flask Backend with SocketIO
  - type: web
    name: poker-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      - key: OPENAI_API_KEY
        sync: false  # Set in Render dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: poker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: poker-redis
          type: pserv
          property: connectionString
    healthCheckPath: /health
    
  # React Frontend
  - type: web
    name: poker-frontend
    runtime: static
    buildCommand: cd react/react && npm install && npm run build
    staticPublishPath: ./react/react/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options  
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        
  # Redis for session management
  - type: pserv
    name: poker-redis
    runtime: docker
    dockerfilePath: ./Dockerfile.redis
    dockerContext: .
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: poker-db
    plan: free  # PostgreSQL free tier
    databaseName: poker
    user: poker_user