"""Extract the v1..v157 integer chain from schema_manager.py into legacy_migrations.py.

Phase-3 squash step. Moves `_run_migrations` (dict + self-heal blocks + loop) and
every `_migrate_vN` method into a `LegacyMigrations` class, leaving schema_manager
with a thin delegator. Behaviour is identical: the delegator runs the same chain,
now relocated. Every transform asserts its match count, so a drifted source fails
loudly instead of silently mangling the file.

Run from repo root:  python scripts/_extract_legacy_migrations.py
"""

import re

SM = "poker/repositories/schema_manager.py"
OUT = "poker/repositories/legacy_migrations.py"

lines = open(SM).read().splitlines(keepends=True)


def find(prefix):
    hits = [i for i, ln in enumerate(lines) if ln.startswith(prefix)]
    if len(hits) != 1:
        raise SystemExit(f"expected exactly 1 line starting {prefix!r}, found {len(hits)}")
    return hits[0]


i_run = find("    def _run_migrations(self) -> None:")
i_v1 = find("    def _migrate_v1_add_owner_columns(self,")
assert i_run < i_v1, "(_run_migrations must precede _migrate_v1)"

# Sanity: from the first migration method to EOF, every top-level method is a migration.
for ln in lines[i_v1:]:
    if ln.startswith("    def ") and "_migrate_v" not in ln:
        raise SystemExit(f"non-migration method inside the extracted block: {ln.strip()!r}")
# Sanity: no stray module-level (col-0) code after the block.
for ln in lines[i_v1:]:
    if ln.strip() and not ln.startswith((" ", "\t")):
        raise SystemExit(f"unexpected top-level line in block: {ln.strip()!r}")

head = "".join(lines[:i_run])
run_block = "".join(lines[i_run:i_v1])
methods = "".join(lines[i_v1:])


def repl(text, old, new, n=1):
    c = text.count(old)
    if c != n:
        raise SystemExit(f"expected {n}x {old!r}, found {c}")
    return text.replace(old, new)


# Transform _run_migrations -> LegacyMigrations.run(connection_factory, current, target).
rb = run_block
rb = repl(
    rb,
    "    def _run_migrations(self) -> None:",
    "    def run(self, connection_factory, current_version: int, target_version: int) -> None:",
)
rb = repl(
    rb,
    '        """Run any pending schema migrations."""\n',
    '        """Apply the archived chain to bring a sub-baseline DB to target."""\n',
)
# Drop the self-fetch of current_version (now a parameter).
rb2 = re.sub(r"[ \t]*current_version = self\._get_current_schema_version\(\)\n", "", rb, count=1)
assert rb2 != rb, "current_version fetch line not found"
rb = rb2
rb = repl(rb, "if current_version >= SCHEMA_VERSION:", "if current_version >= target_version:")
rb = repl(
    rb,
    'f"Running database migrations from version {current_version} to {SCHEMA_VERSION}"',
    'f"Running legacy migrations from version {current_version} to {target_version}"',
)
rb = repl(rb, "self._get_connection()", "connection_factory()")
rb = repl(
    rb,
    "for version in range(current_version + 1, SCHEMA_VERSION + 1):",
    "for version in range(current_version + 1, target_version + 1):",
)

legacy = '''"""Archived legacy schema migrations — the frozen v1..v157 integer chain.

GENERATED by scripts/_extract_legacy_migrations.py at the v157 squash; do NOT edit
by hand. Lifted verbatim from schema_manager.py (the `_migrate_vN` methods only use
their `conn` arg, so they relocate unchanged).

Runs ONLY for a sub-baseline database — e.g. a restored pre-baseline backup. Fresh
installs build the head schema directly via SchemaManager._init_db (schema_baseline)
and are stamped at the baseline, so this chain is skipped. New migrations are
authored as files under migrations/ (see migration_loader).
"""

import json
import logging
import random
import sqlite3
from typing import Dict

from poker.personality_id import (
    assign_unique_personality_id as _assign_unique_personality_id,
    slugify_personality_name as _slugify_personality_name,
)

logger = logging.getLogger(__name__)


class LegacyMigrations:
    """The frozen v1..v157 integer migration chain, lifted from SchemaManager."""

'''

legacy += rb
if not legacy.endswith("\n"):
    legacy += "\n"
legacy += "\n"
legacy += methods

with open(OUT, "w") as f:
    f.write(legacy)

# Rewrite schema_manager: replace _run_migrations + all methods with a delegator.
delegator = '''    def _run_migrations(self) -> None:
        """Bring a sub-baseline DB up to the baseline via the archived legacy chain.

        Post-squash, fresh DBs are stamped at SCHEMA_VERSION by ``_init_db`` and skip
        this entirely; it only fires for a restored pre-baseline backup. The frozen
        v1..v157 integer chain lives in ``poker/repositories/legacy_migrations.py``.
        """
        current_version = self._get_current_schema_version()
        if current_version >= SCHEMA_VERSION:
            return
        from poker.repositories.legacy_migrations import LegacyMigrations

        LegacyMigrations().run(self._get_connection, current_version, SCHEMA_VERSION)
'''

new_sm = head
if not new_sm.endswith("\n"):
    new_sm += "\n"
new_sm += delegator
with open(SM, "w") as f:
    f.write(new_sm)

print(
    f"legacy_migrations.py: {legacy.count(chr(10))} lines, "
    f"{legacy.count('def _migrate_v')} migration methods"
)
print(f"schema_manager.py: {new_sm.count(chr(10))} lines (was {''.join(lines).count(chr(10))})")
